# Engine: Schlüssel für die Tokens des Webclients.
# Schulung: eigener Schlüssel, nur lokal. Muss gleich common.jwt.secret in common-config.yaml sein.
cibseven.webclient.authentication.jwtSecret=0eb49dd5349dcd8620ab00c0e1568347070149d209bda7b23eee440e9462d543981e1dc4374df057ccdfde0512d36d2eced0f446f1bf17d96fecd379197f0bb0
cibseven.webclient.authentication.groupsOfUserValidMinutes=30
